### ISSUE TITLE
Support NetCoreApp 3.0 / .Net Core 3.0

### ISSUE THREAD

**Issue by ITHedgeHog** [martinjt/honeycomb#10]
Hi, do you have any plans to release a version compatible with .Net Core 3.0? If so when might we see it?

The SDK is now available with a go-live license which has prompted us to start investigating the upgrade process, currently, we cannot upgrade any application which reports to Honeycomb until this is done.

If it's not on your radar, I'll happily work up a pull request to enable this?

**Comment by martinjt** [comment]
Wouldn't that be compatible with what's there... Happy to look at it, but I
figured that it would "Just Work" (tm).

**Comment by ITHedgeHog** [comment]
What would you know, it fails through the Nuget Package Manager UI but works perfectly well when I do it via the command line, will raise a bug with the Visual Studio team as this is the case.

You're right - it does just work. 

For reference via the UI it would complain that this package was for NetStandardApp 2.1, not netstandard 2.0 when installing via the UI.
