### ISSUE TITLE
Span IDs and Span context propagation is missing

### ISSUE THREAD

**Issue by irvingpop** [martinjt/honeycomb#15]
@danyelf and I noticed that Honeycomb doesn't detect events from this library as traces, most likely because `trace.span_id` and `trace.parent_id` aren't generated and sent along

**Comment by danyelf** [comment]
Perhaps this is a docs fix? A little more documentation or an exemplar of how to set up tracing data would be lovely.

**Comment by martinjt** [comment]
The idea of this library is not traces.  It's a communication library that simply manages the communication with honeycomb.  It will not emit any events itself.  There is the AspNetCore implementation that wraps the HttpRequest, but this is not for tracing, just normal events.

The opentelemetry implementation is separate, in https://github.com/martinjt/Honeycomb.OpenTelemetry.

If OpenTelemetry, and it's Collectors retrieve traces from the Http calls this library makes, then OpenTelemetry would add all the relevant data to the events.
